### ISSUE TITLE
prompt instructions appear in output if canary relaunches and non-empty input textarea is cleared

### ISSUE THREAD

**Issue by fitsum** [tomayac/prompt-api-playground#1]
when I relaunch Chrome and the playground's input field is not empty, ie. I summarized some text and for some reason had to relaunch the browser, if I clear the input the summarization appears to run but what's generated (below) appears to be instructions for summarizations

> - Summarize the key points of the provided text into five bullet points. - Each bullet point should be one complete sentence and accurately reflect the main ideas of the text. - **Key points:** - **- Provide a brief overview of the overall topic of the text.** * For example: "This report discusses the impact of climate change on energy production." - **- Summarize the main idea of the first paragraph.** * For example: "Climate change is significantly affecting energy production, leading to concerns about energy security and sustainability." - **- Briefly describe the main idea of the second paragraph.** * For example: "Technological advancements and innovations in energy production offer promising solutions to mitigate the negative impacts of climate change and enhance sustainability." - **- Summarize the main point of the third paragraph.** * For example: "Governments and organizations are implementing policies and initiatives to encourage the shift towards renewable energy sources, reducing greenhouse gas emissions and transitioning to a greener energy future." - **- Conclude the summary by summarizing the overall main idea of the text.** * For example: "In conclusion, the report emphasizes the critical need to address climate change and transition to sustainable energy practices to ensure a prosperous and resilient future for all."

**Comment by tomayac** [comment]
This is essentially running the following code:

```js
const summarizer = await ai.summarizer.create();
await summarizer.summarize('');
```

I agree that the summarization of the empty string should not reveal parts of the system prompt. I will file an internal bug. Thanks for the report.
