### ISSUE TITLE
a PlayGround for all Chrome AI APIs

### ISSUE THREAD

**Issue by oslook** [tomayac/prompt-api-playground#3]
I made a Playground for all APIs with the latest Chrome AI API for everyone to use. 
The latest version of the API function will be continuously updated in the future.

https://github.com/oslook/chrome-ai-playground

The implementation of the following APIs has been completed: 
- **Prompt** - Interactive chat interface for testing prompts
- **Summarize** - Text summarization capabilities
- **Translate** - Language translation functionality
- **Detect Language** - Automatic language detection
- **Writer** - AI-powered writing assistance
- **ReWriter** - Content rewriting and refinement

**Comment by tomayac** [comment]
This is a fantastic playground! My repository is the wrong place to announce it, though. Could I ask you to send this to [mailto:chrome-ai-dev-preview-discuss@chromium.org](chrome-ai-dev-preview-discuss@chromium.org)? Thanks!

**Comment by oslook** [comment]
> This is a fantastic playground! My repository is the wrong place to announce it, though. Could I ask you to send this to [chrome-ai-dev-preview-discuss@chromium.org](mailto:chrome-ai-dev-preview-discuss@chromium.org)? Thanks!

I was just about to submit a topic to the Discuss group, but I can't seem to because I don't have permission.

**Comment by tomayac** [comment]
You need to join the group first: https://groups.google.com/a/chromium.org/g/chrome-ai-dev-preview-discuss/about?pli=1.
